### ISSUE TITLE
大佬，有使用说明不？能直接引用吗？压缩完成能替换掉源文件吗？

### ISSUE THREAD

**Issue by huaxuanHan** [FDoubleman/LubanPlus#1]

**Comment by huaxuanHan** [comment]
在Android13上面运行有问题吧

**Comment by FDoubleman** [comment]
您好：
    前些天有点忙，
    使用文档已经完善，使用方法已经再文档内。

    1、压缩完成后替换原来的文件，是可以的。
        请描述 功能使用场景后，决定是否添加该功能。
    
    2、Android 13上运行有什么问题？请提供运行环境和详细日志。 
    3q

**Comment by huaxuanHan** [comment]
感谢
