### ISSUE TITLE
建议，希望能设置压缩后的文件最大值

### ISSUE THREAD

**Issue by huaxuanHan** [FDoubleman/LubanPlus#2]
我之前用的是https://github.com/jackyHuangH/AdvancedLuban这个，调用也是很简单的，直接设置压缩后的文件最大值就可以了，因为设置压缩质量在不同的设备上压缩后的文件大小不好控制

Luban.compress(context, file)       // 初始化Luban，并传入要压缩的图片
.putGear(CompressGear.LUBAN_GEAR)      // 设定压缩模式，默认 LUBAN_GEAR
.setMaxSize(400)
.launch(listener);

**Comment by FDoubleman** [comment]
你好：
      你提出的添加 “设置压缩后的文件最大值” 功能已经实现。请具体使用参考1.0.2版本和README 。谢谢
