### ISSUE TITLE
gradle里面不能引用

### ISSUE THREAD

**Issue by huaxuanHan** [FDoubleman/LubanPlus#3]
implementation 'io.github.FDoubleman:LubanPlus:1.0.2'不能正常的引用，麻烦看一下咋回事

**Comment by FDoubleman** [comment]
![image](https://user-images.githubusercontent.com/16278122/226857088-391fab41-0e30-4883-8be5-60bc2c0840a2.png)
刚尝试 引用了  implementation 'io.github.FDoubleman:LubanPlus:1.0.2'  并未发现有问题，

请确保添加  root->build.gradle 文件 添加了    mavenCentral() 的仓库配置。

repositories {
        google()
        mavenCentral()
    }
